name: "another-mp2i-bot"

services:
  mp2i-bot:
    container_name: mp2i-bot
    init: true
    tty: true
    restart: no
    build:
      target: debug
      context: .
      dockerfile: $PWD/Dockerfile
    ports:
      - 5678:5678
    environment:
      CTS_TOKEN: ${CTS_TOKEN}
      BOT_TOKEN: ${BOT_TOKEN}
      OPENWEATHERMAP_API_KEY: ${OPENWEATHERMAP_API_KEY}
      OPENIA_API_KEY: ${OPENIA_API_KEY}
    volumes:
      - $PWD/data:/app/data
      - $PWD/config.toml:/app/config.toml
      - $PWD/external_data:/app/external_data
    develop:
      watch:
        - action: sync
          path: ${PWD}/src
          target: /app
        - action: rebuild
          path: ${PWD}/uv.lock
        - action: rebuild
          path: ${PWD}/config.toml
        - action: rebuild
          path: ${PWD}/.env
